<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BatteryHub.Core\BatteryHub.Core.csproj" />
  </ItemGroup>

</Project>
